# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af6780c46f452574556d96f744bcc5918a505d2d40727b27d4662468cca7709e6557e0c6b83d7da8a2e1f6b461e23a6d72e5ff3996ebe54d0ceebec92fdeb835

test:
  secret_key_base: 4527355abe8c7e2fae2b16e2da2de4b982937efc7f5b2f2662085602aa96229f7f283441ad9ea9b370a8a5644ae25017476997eb5b3ba4b62b8b1f293978682f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
